# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-31 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daychangers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordernumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('series', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='stocksearch',
            name='series',
        ),
        migrations.AddField(
            model_name='orderbook',
            name='orderno',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
