# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-31 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daychangers', '0003_remove_ordernumber_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='ordertype',
            field=models.CharField(default='market', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderbook',
            name='status',
            field=models.CharField(default='success', max_length=100),
            preserve_default=False,
        ),
    ]
