# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-01 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daychangers', '0004_auto_20170801_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendingorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('trade_type', models.CharField(max_length=250)),
                ('orderno', models.IntegerField()),
                ('ordertype', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
